This first block is to load the standard builtin MNIST objects. Note that they are Datasets, but they are a subclass, MNIST. These Datasets are what we want to synthesize.

In [31]:
import torch
import torchvision.datasets as dsets

import torchvision.transforms as transforms
#trans = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (1.0,))])
trans = transforms.Compose([transforms.ToTensor()])

# pytorch datasets that download MNIST set as needed; used only to download files
builtin_train_dset = dsets.MNIST(root=data_path, download=False, train=True, transform=trans)
builtin_test_dset = dsets.MNIST(root=data_path, download=False, train=False, transform=trans)


len(builtin_test_dset)
repr(builtin_test_dset)
builtin_test_dset.__getitem__(0)

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

Now we try to build our own from a numpy array

In [32]:
data_path = './MNIST-data/raw'

# location of data and labels
test_labels_file = data_path + '/' + 't10k-labels-idx1-ubyte'
test_data_file = data_path + '/' + 't10k-images-idx3-ubyte'
train_labels_file = data_path + '/' + 'train-labels-idx1-ubyte'
train_data_file = data_path + '/' + 'train-images-idx3-ubyte'

In [43]:
import numpy as np
import struct

def read_idx(filename):
    with open(filename, 'rb') as f:
        zero, data_type, dims = struct.unpack('>HBB', f.read(4))
        shape = tuple(struct.unpack('>I', f.read(4))[0] for d in range(dims))
        return np.frombuffer(f.read(), dtype=np.uint8).reshape(shape)
    
# read data and label files into numpy arrays
test_data = read_idx(test_data_file)
test_labels = read_idx(test_labels_file)
train_data = read_idx(train_data_file)
train_labels = read_idx(train_labels_file)

In [44]:
# print some arrays to confirm we have data
#print("Test labels:", test_labels)
#print("Test data:", test_data[0])
#print("Training labels:", train_labels)
#print("Training data:", train_data[0])

print(test_labels.shape)
print(test_data.shape)

(10000,)
(10000, 28, 28)


In [50]:
# load numpy arrays into pytorch Datasets
import torch
from torch.utils.data import TensorDataset
from torchvision.datasets import MNIST


# create tensors from np arrays
test_data_tensor = torch.from_numpy(test_data)
test_labels_tensor = torch.from_numpy(test_labels)
train_data_tensor = torch.from_numpy(train_data)
train_labels_tensor = torch.from_numpy(train_labels)

#print(test_data_tensor)
print(test_labels_tensor)

test_labels_tensor[1]

tensor([7, 2, 1,  ..., 4, 5, 6], dtype=torch.uint8)


tensor(2, dtype=torch.uint8)

In [52]:
# load tensors into datasets
#test_dset = TensorDataset(test_data_tensor, test_labels_tensor)
#train_dset = TensorDataset(train_data_tensor, train_labels_tensor)

#print("test_dset:",
#      test_dset,
#      len(test_dset), test_dset[0][0].size(), type(test_dset[0][0])
#     )

# TODO - MIKE load into type torchvision.datasets.MNIST ?
# see https://pytorch.org/docs/stable/torchvision/datasets.html#mnist


test_dset.__getitem__(0)

(tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   0,   0,   0,

In [40]:
x = np.array([1,2,3])
print(x)
xt = torch.from_numpy(x)
print(xt)

[1 2 3]
tensor([1, 2, 3])


In [16]:
import torch
import torchvision.datasets as dsets

import torchvision.transforms as transforms
trans = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (1.0,))])
#trans = transforms.Compose([transforms.ToTensor()])

# pytorch datasets that download MNIST set as needed; used only to download files
builtin_train_dset = dsets.MNIST(root=data_path, download=False, train=True, transform=trans)
builtin_test_dset = dsets.MNIST(root=data_path, download=False, train=False, transform=trans)


len(builtin_test_dset)
repr(builtin_test_dset)
builtin_test_dset.__getitem__(0)

(tensor([[[-0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
          [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
          [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
          [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000, -0.5000,
           -0.5000, -0.5000, -0.500